# 项目点路由
service:
  - name: "商家组织维护"
    path: "travel_org/index.yml"
  - name: "销售客服维护"
    path: "sales_cs_user/index.yml"
  - name: "客户管理与分配"
    path: "customer_assign/index.yml"
  - name: "用户管理"
    path: "user/index.yml"
  - name: "角色管理"
    path: "role/index.yml"


  - name: "ldap"
    path: "ldap/index.yml"

  - name: "login"
    path: "login/index.yml"
  - name: user_flow
    path: "user_flow/index.yml"
  - name: user_role
    path: "user_role/index.yml"
  - name: ldap_group
    path: "ldap_group/index.yml"
  - name: role_ldap_group
    path: "role_ldap_group/index.yml"

  - name: user_change_history
    path: "user_change_history/index.yml"

  - name: "旅行社数据同步"
    path: "sync_agency_data/index.yml"

  - name: "通讯录"
    path: "travel_chat_contact/index.yml"
  
  - name: "聊天记录"
    path: "travel_chat_record/index.yml"
  
  - name: "电话记录"
    path: "travel_call_record/index.yml"

  - name: "逃单检测"
    path: "detect_escape/index.yml"
  - name: "腾讯Key申请"
    path: "tencent_key/index.yml"
