insert into travel_employee(
  employee_id,
  agency_id,
  alias,
  head,
  nick_name,
  ower_wx_alias,
  phone,
  phone_user,
  user_id,
  wx_id,
  wx_target,
  status,
  description,
  create_time,
  create_user
) values (
  {{.employee_id}},
  {{.agency_id}},
  {{if .alias}}{{.alias}}{{else}}NULL{{end}},
  {{if .head}}{{.head}}{{else}}''{{end}},
  {{if .nick_name}}{{.nick_name}}{{else}}''{{end}},
  {{if .ower_wx_alias}}{{.ower_wx_alias}}{{else}}''{{end}},
  {{if .phone}}{{.phone}}{{else}}''{{end}},
  {{if .phone_user}}{{.phone_user}}{{else}}0{{end}},
  {{if .user_id}}{{.user_id}}{{else}}0{{end}},
  {{if .wx_id}}{{.wx_id}}{{else}}''{{end}},
  {{if .wx_target}}{{.wx_target}}{{else}}1{{end}},
  {{if .status}}{{.status}}{{else}}'normal'{{end}},
  {{if .description}}{{.description}}{{else}}''{{end}},
  {{if .create_time}}{{.create_time}}{{else}}''{{end}},
  {{if .create_user}}{{.create_user}}{{else}}''{{end}}
)